### PR TITLE
Update Italian Localization

### PR DESCRIPTION
**Pull request by Arc676**
I've always modified translations directly in Xcode. Also XLIFFTool doesn't seem to work; I tried opening the included XLIFF file in #915 but it never responded, so I just edited the strings files directly. Let me know if that causes any issues.

The original strings file was missing multiple entries and had reordered the strings, so I overwrote the file completely to match the ordering in the English and German versions. Where possible, I reused the already present translations unless I felt they could be improved.

### Needs Adressing
- [ ] Line 169: it's not clear what "Clear Autotype" is meant to do. The German translation doesn't provide a unique interpretation (as far as I can tell) and I couldn't find translation in any other languages I speak.
- [ ] Line 520: output value of what?

### CODE REVIEW

**Comment by michelecos** [comment]
Looking at the diffs I would say you did an excellent work

**Comment by mstarke** [comment]
I've update the comments in the code. What makes me wonder is why you did not get XLIFFTool to work, it does work for me with no problems. Can you specify what went wrong?

I've also re-started trying to get lokalize.co to work with MacPass but there are still some stange things going on until I can get this to work.

Regarding your questions:

Line 169: This is a UI that is not used anymore which was introduced in 0.5 to fix broken Autotype value. I might just clear it since it is not necessary anymore. What this is is the label for a button to clear the auto-type value for the selected entry which then enabled the default again.
Line 520: This is a currently unused UI to create a reference. The output value is the field you want to reference. E.g. if you want to reference the Username from another Entry, Username is the output value.

**Comment by mstarke** [comment]
There are more localisation changes coming along so you might want to re-run your setup. I'm trying to get 0.7.10 out of the door with many of the localisation stuff being fixed.

**Comment by Arc676** [comment]
I'm not really sure what went wrong. I tried opening the XLIFF file both from within XLIFFTool with Ctrl+O (or from menu) and by dragging it onto the Dock icon but nothing ever appeared.

Thanks for the explanations regarding the two UI elements.

I'll pull and rebase with the new changes and update this PR when I have time.

**Comment by mstarke** [comment]
I just exported the XLIFF on my branch and it worked flawlessly. Can you try to open the attached file?
[it.xliff.zip](https://github.com/MacPass/MacPass/files/3529883/it.xliff.zip)

**Comment by mstarke** [comment]
I dug into online localization via lokalize.co again and it seems to work better than the last time I tried it. I could add you as a contributor so you’ll be able to update the localization there. If you are willing to do so I will merge this PR first, update the strings at lokalise.co and then ping you.

**Comment by Arc676** [comment]
Maybe for the next one. I'm already making good progress just updating the translations from within Xcode. For this PR, I'll just finish up locally then push. Thanks though.

**Comment by Arc676** [comment]
Updated translations. I also took the liberty of
- fixing a typo in the English ("mismatching" instead of "missmatching")
- adding a missing window title in the German localization (suggested: Eintragreproduktionseinstellungen)
- fixing a French translation (was translated as "duplicate the entry settings")

**Comment by mstarke** [comment]
Awesome. I'm updating the lokalize.co stuff with your changes. Regarding the german one that's way off. Made me laugh so thanks for that :-). I've took the liberty to change it to "Optionen zum Duplizieren des Eintrags" which seems way to complicated.

**Comment by mstarke** [comment]
Regarding you bug about XLIFFTool - I had a custom build since my PR was stale for a while and now I updated to the AppStore version and had the exact same problem - no xliff file would get opened. I ran Xliff tool from the commandline via ```/Applications/XLIFFTool.app/Contents/MacOS/./XLIFFTool``` and viola, after that is did open my files. I have no idea what the problem was. Maybe you can try that too and see if it works for you.

**Pull request merged**
