### PR TITLE
Improved Dutch localization

### PR DESCRIPTION
**Pull request by FrankKooij**
**Please keep this pull request open until your next release.**

Dear Michael,

Based on how my translation #714 / #715 / #751 works out in your latest continuous release of 3 March 2018, I made some additional improvements. There may be more tweaks coming, so please keep this pull request open until just before your next release.

Best regards!
Frank

### CODE REVIEW

**Comment by mstarke** [comment]
I'm preparing 0.7.4 for release, there are some minor changes to the localisation. Can you rebase and update your PR? Thad'll be awesome!

**Comment by FrankKooij** [comment]
First time updating from a remote branch. Did commit ecb2780011d0ea7eb2675cd4750fdffd07fc8276 do what you asked for? There were no conflicts.

**Comment by mstarke** [comment]
It did. But I just realised I didn't push all changes that affect localisations. So *erm* you might want to do that once more and re-run your translation workflow to make sure you do get all the new/changes keys.

**Comment by FrankKooij** [comment]
Done. I see that you deleted some lines from `MacPass/MacPass/nl.lproj/Localizable.strings`, but there are no new texts, so no need for additional translations in this release. BTW I also fixed a single typo in `MacPass/MacPass/MPDocument.m`. You may want to double check this yourself.

**Comment by mstarke** [comment]
There are indeed some changes and additional keys but I haven't added them to the ```nl.lproj/Localizeable.string``` file since this should be done by the translator. This has the additinal benefit of the UI plainly showing missing string (by rendering the Placeholders). The simplest way to get the file updated is to use the workflow described here: https://github.com/MacPass/MacPass/blob/master/CONTRIBUTE.md. If you open the XLIFF file you will see all (empty) translations which you then can update, re-import into MacPass using Xcode and you're good to got.

**Comment by mstarke** [comment]
Btw. thanks a lot for the effort you put into this!

**Comment by FrankKooij** [comment]
Could you indicate where I can find the Character Picker and the Field Picker in MacPass? Many of the items that have not been translated yet appear to be related to these pickers.

**Comment by mstarke** [comment]
Those items aren't finished yet and are UI for Keepass fields.

You can get them to show up if you put ```{PICKCHARS}``` and ```{PICKFIELD}``` in e.g. the username and then copy the username. A dialog will pop up to allow you to pick characters or pick a field. If you need more info on them, feel free to ask.

**Comment by mstarke** [comment]
I'm finishing up 0.7.4 so could you rebase and resolve any conflicts?

**Comment by FrankKooij** [comment]
I resolved potential merge conflicts by reinserting trailing whitespace that had been automatically removed by my editor. Unfortunately I have not had access to Xcode since last summer. Unless someone can help me get the necessary XLIFF files, further localization improvements will have to wait.

**Comment by mstarke** [comment]
Here's the current xliff for MacPass. If you find the time to update the file it woudl be awesome.
[nl.xliff.zip](https://github.com/MacPass/MacPass/files/2855668/nl.xliff.zip)

**Comment by FrankKooij** [comment]
Thanks for the attaching the xliff file. Still some 135 entries out of 577 to go... How much time until the 0.7.4 release? Also, what happens when a translation is missing, i.e. blank? Will the software automatically use the original (English) text?

**Comment by mstarke** [comment]
No pressure. I have no time frame for the release since I tend to miss them all the time. So just take your time. If something is blank, the system will display the key so it's not falling back to english. This is rather unpleasant, but this way missing translations are spotted more easily.

If you do not get to translating everything, I can just paste in the english version so there's at least a decent text being displayed.

Again, thank you for you efforts!

**Comment by FrankKooij** [comment]
Am I overlooking something or are some strings missing from the xliff file, e.g. `WebDAV URL` and `TOOLBAR_PERFORM_AUTOTYPE_FOR_ENTRY`?

**Comment by mstarke** [comment]
WebDAV URL should not be anywhere. TOOLBAR_PERFORM_AUTOTYPE_FOR_ENTRY is present. You have to look for the Comment since the english translations is just Autotype.

**Comment by FrankKooij** [comment]
You will find a partially updated [nl.xliff](https://github.com/MacPass/MacPass/files/2898405/nl.xliff.zip) in the attachment. The remaining translations are quite difficult because it is not quite obvious if and where these strings are used in the UI. Further refinement may therefore take some time.

**Comment by mstarke** [comment]
I'm merging this and adding the changes from the xliff import in a separate commit. Thank you for your work!

**Comment by FrankKooij** [comment]
Please find additional improvements in the attached [nl.xliff](https://github.com/MacPass/MacPass/files/2946867/nl.xliff.zip).

**Comment by FrankKooij** [comment]
@mstarke Please find additional improvements in the attached [nl.xliff](https://github.com/MacPass/MacPass/files/3002353/nl.xliff.zip).

**Comment by FrankKooij** [comment]
All localization improvements prior to today are included in the attachment to #902.

**Pull request merged**
