### PR TITLE
Translation to spanish improved

### PR DESCRIPTION
**Pull request by buttcmd**
- Translation to Spanish of the new functionalities (adapt to new Localizable strings order) (English flie used as source)
- Corrections of some typos in English translation

### CODE REVIEW

**Comment by mstarke** [comment]
If you have access to Xcode the better way is to export the localization, edit it with a XLIFF tool and then re-import. This way you get updates to UI files as well since they are missing from the localizeable files. If you find the time you might push those changes to this PR

**Comment by buttcmd** [comment]
All the translations have been completed. You where right with XLIFF was easier

**Comment by mstarke** [comment]
Awesome! I'm currently shuffling some UI aroung so there might be some changes in the future that will need more updates. Would it be ok for you if I ping you to ask for an update?

**Comment by buttcmd** [comment]
No problem! The hard work is already done and I am a heavy user of the app so it worths the effort

Saludos,
César.

**Comment by skyline75489** [comment]
The zh-Hans translation is very outdated. I'm trying to update the Simplified Chinese translation using the xlifftool way. 

I found there are some duplicate entrys. Some entrys seems to be unused, though. @mstarke Is there any plan to fix those. I found it confusing for tranlators like me.

**Comment by mstarke** [comment]
I've tried to update as many translations as possible to use only used strings but I haven't touched Chinese. I will try to set this up so you can get on updating the translations. Awesome by the way!

**Pull request merged**
