### PR TITLE
[LaunchOnLogin] 

### PR DESCRIPTION
**Pull request by georgesnow**
Adds helper app for launching MacPass on login. This is prerequisite to start the process of moving MacPassRevealer's core functionality into MacPass. The plan is to provide the ability to have a NSStatusItem(menubar icon), hide the dock icon, and hotkey for revealing(hiding/unhiding) MacPass. And for these to work best having the app launch on login is required.

### CODE REVIEW

**Comment by georgesnow** [comment]
need to adjust deployment target on the helper.app to 10.11

**Comment by mstarke** [comment]
0.7.x should still run on 10.10. Raising this will happen in 0.8 so this PR has to wait a bit.

**Comment by georgesnow** [comment]
my mistake. I thought MP 0.7.x was set to run on 10.11. I can adjust the helper.app to 10.10 to make it compatible with 0.7.x.

**Comment by georgesnow** [comment]
@mstarke 0.8.x makes sense for this feature. I want to try and wrap up all the pieces with this. The menu bar icon (status bar) and hiding the dock icon all completed with this for 0.8.x. 

I noticed I need to app the icon for helper.app as well as some more clean up. I am hoping someone else might try building this commit and testing it. I have tried on the 2 machines I can. One Mojave and the other Catalina.

**Comment by georgesnow** [comment]
need to clean this up. I noticed there have been changes since I started this merge request.

**Comment by georgesnow** [comment]
so I tried resolving the conflicts, but it appears GitHub blew away this branch on my repo. And I can't seem to pull this conflicted version to re-create my branch on my repo...hmmm🤔

**Pull request closed without merging**
