### PR TITLE
fixed autofill on big sur for password field

### PR DESCRIPTION
**Pull request by mcaserta**
Apple enabled password autofill by default on Big Sur for NSSecureTextField.

This means that by clicking the password field in an entry in MacPass, an annoying "Passwords..." tooltip pops up.

By changing the secure text field's content type to "oneTimeCode", the default behavior is overridden and the autofill feature is disabled.

### CODE REVIEW

**Comment by mstarke** [comment]
One time code smells but it seems to do the trick. Might it be possible to use None as the content type? Or is this hard-coded into NSSecureTextField?

**Comment by mcaserta** [comment]
I know it stinks, I hate it too. I believe "None" is the default content type, as that's what shows up in the attributes inspector in XCode before my change and it shows the offending behavior. I'm not a mac developer so I don't know where to look up all of NSSecureTextField's attributes... maybe there is an autofill kill switch there.

**Comment by mylemans** [comment]
It would be nice to see this change in an update, as this is bothering the heck out of me (feels like I have to 'fight' this popup all the time when trying to add a new entry)

**Comment by JorisBodin** [comment]
Any idea when it will be in production? :D

**Pull request merged**
