### PR TITLE
Improved Dutch localization (using XLIFF)

### PR DESCRIPTION
**Pull request by aiolos**
This is a combined version of #713 and #714. I used the branch from @FrankKooij and exported the XLIFF file. 
A few missing translations were also added and the XLIFF is imported in the project again.

The accidentally overwritten translations are reverted.

### CODE REVIEW

**Comment by aiolos** [comment]
This PR and #714 are now open for a while. I would suggest to merge or close the PRs, because they can become outdated if other functionality is merged. 
As stated before: this PR combines the good translations of #714 (the commits are still in there and accidental errors are reverted) and also makes use of the XLIFF method of translating.
Translations are not complete: not with this PR and not with #714, but already much better than before. After merging we can continue with translations and as such making MacPass better and better.

**Comment by mstarke** [comment]
I had no time over the holidays to look into this. I will try to sort through this. I had the intention that all contributors come to a final pull request which is mergeable and the rest gets closed by the authors.

**Comment by aiolos** [comment]
No problem, I just created this PR with the same intention (and closed #713). This PR is basically #714 but with the use of XLIFF import/export.

**Comment by FrankKooij** [comment]
Sorry for the delay. There was no time for coding over the holidays. When I [compare the last commit of #715 with the last commit of #714](https://github.com/mstarke/MacPass/compare/741ea1c1c23892cf554f1de0516ea292c3bd0ec3...7b3743c94c697bbb090b052de8f2a125e12b2b3d) many translation improvements appear to be missing in #715. You can close #714 if these improvements are also added to #715.

**Comment by aiolos** [comment]
I fixed some translations that were removed and added a few more. If there is any missing translation left, let me know where in the interface that is. I clicked through the whole application and cannot find any missing translations right now.

**Comment by mstarke** [comment]
I'm going to close #714 an merge this.

**Pull request merged**
