### PR TITLE
Improved Dutch localization

### PR DESCRIPTION
**Pull request by FrankKooij**
Dear Mr. Starke,

Please find an improved Dutch language localization in this pull request. I tried to be consistent, honour Dutch spelling and style, and at the same time follow localized phrases as used by Apple and Mozilla. Although this branch includes an import of missing strings from the English language folder into the Dutch language folder, there still appear to be multiple strings missing from these localization folders (e.g. `FILE_CHANGE_STRATEGY_ASK`) and also these folder appear to contain multiple obsolete strings (e.g. `Item 3`).

Unfortunately I have been unable to test whether my strings fit into the text spaces that are available. Some may be too long and still need some editing.

Keep up the good work!

Best regards,
Frank

### CODE REVIEW

**Comment by mstarke** [comment]
Hello Frank. Thank you for you work, as I have already mentioned in PR #713 using XLIFF export and import is a good way to localise MacPass. This way you only end up with no missing string. However, as you have mentioned, some obsolete string will still be present but removing those is a lot more cumbersome. I plan to update a lot of the .strings files for interfaces since they are the ones with dead key but this involves re-adding localisations and some manual synchronisations which I haven't had the time for. This is mostly cruft from refactoring views but since the UI of MacPass is pretty stable I might put in the work.

And a final note: How do we work with both PRs? I have no clue which one to use? Should I merge one and then the other gets merged in as well after a rebase?

**Comment by mstarke** [comment]
Regarding your comment about text spaces: The UI is laid out with Autolayout so no string should break it, if this happens this needs to be fixes by adjusting the layout and **not** by changing the localisation.

**Comment by aiolos** [comment]
I tried to combine both this PR and #713. When I import the XLIFF file also some strings will be removed. I don't think this is really a problem, since they are not used anyway.

I also found some place where autolayout doesn't seem to work ok. I saw it last night, and don't have it available right now. I will show it later.

**Comment by aiolos** [comment]
See #715

**Comment by FrankKooij** [comment]
Pull request #713 appears to be an refinement of the original localization by @clone1612. Both localizations still contain many English (e.g. `Restore Entry`, `Toolbar`, `Trash`) and technical terms (e.g. `Keyfile`, `Database`), and also spelling errors such mid-word spaces and mid-sentence capital letters (e.g. `Activeer Input Geschiedenis`).

Apple and Mozilla use spelling conventions when localizing software. They use a standard vocabulary and always start button texts with a verb. Pull request #714 attempts to adher to spelling conventions like these and consequently is a complete overhaul of the original translation.

As far as I can tell #715 introduces many changes to #714, both additions and deletions. Some appear to reverse what #714 attempts to achieve, e.g.:

- `Tekenreeks instellen` (noun + verb, #715) instead of `Bewaar tekenreeks` (verb + noun, #714);
- `Beschikbare commando's en placeholders` (English + technical, #715) instead of `Beschikbare invoer en variabelen` (Dutch, #714)

Other changes most likely come from XLIFF.

@mstarke Please let me know if you wish to pursue the direction of #714 or prefer to keep the original localization with the refinements of #713 or perhaps something in between (#715).

If you decide to opt for the direction of #714, I would be quite happy to continue refining it using feedback from the community. Such feedback already resulted in the changes in commit 741ea1c1c23892cf554f1de0516ea292c3bd0ec3.

**Comment by aiolos** [comment]
Hi,

I agree with using the conventions from Apple and Mozilla. It was not my intention to overwrite your changes, which I think are very good.

However, it turns out that when the translations are done by XLIFF, a lot of changes are being made due to removed or changed variables. That's what happened in #715. 

When I checked out your branch and compiled the application using xcode, some texts didn't look translated in the application, which is probably due to changed variable names. @mstarke Can that be the case?

So I think we should approach this problem by using your translations and using XLIFF, so that when the strings are exported and imported again, they will stay right (otherwise this same problem will occur again). For now, I will compare my last commit in #715 and see what needs reverting.

Btw: If you have any information about how to approach translations following the mentioned conventions, please feel free to update the information in the `contribute.md` file.

**Comment by mstarke** [comment]
Missing Strings might result from outdated string files for .xib files. This is an issue I faced recently and haven't paid attention to. To fix this it seems to be necessary to recreate those string files for all the localized .xibs but I'm not 100% sure. I need to take a look into this. The Localizabel.strings file should be complete however.

**Comment by mstarke** [comment]
Can I close this in favour of #715

**Comment by mstarke** [comment]
Closed, see #715

**Pull request closed without merging**
